version: "3.7"

services:

  app:
    build: .
    command: nodemon index.js -L
    ports:
      - "8080:8080"
    environment:
      DB_CONNECT: mongodb://root:root@mongodb:27017/app?retryWrites=true&w=majority&authSource=admin
      TOKEN_SECRET: euf273rz237zusdfhsufaszefg237fg7z
    depends_on:
      - mongodb
    volumes:
      - ./:/app

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
